### ISSUE TITLE
Controller activates on user click

### ISSUE THREAD

**Issue by Doumda** [OfficeDev/O365-Angular-Profile#1]
MainController activates everytime a user is clicked (causing a fetch of all users), not sure what is causing this.

**Comment by martellaj** [comment]
Thanks for your feedback, Doumda! I wasn't subscribed to my own repo so I'm just seeing this now. I will look into it.

**Comment by martellaj** [comment]
I think this is an ADAL issue. I'm investigating. Thank you.

**Comment by martellaj** [comment]
Thanks, @Doumda! I found the issue. It's a combination of a faulty error code and how our authentication library reacts to it.

**Comment by Doumda** [comment]
Thanks for investigating this!
